### ISSUE TITLE
@RGについてPIをUnknownにしたらエラーとなった。

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#33]
PIをUnknownにしたら、他のツールを実行時にエラーとなりました。
やはり、Unknownにするなら項目自体ない方がよいです。

Picked up JAVA_TOOL_OPTIONS: -XX:+UseSerialGC -Xmx64m -Xms32m
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: net.sf.samtools.SAMFormatException: Error parsing SAM header. PI is not numeric: Unknown. Line:
@RG     ID:NOG9NPG0304  PI:Unknown      CN:HGC  PU:Unknown      PL:Illumina     LB:Unknown      SM:NOG9; File /share/hgc0835/thyroid_project/thyroid_project/results/20150430/PG0304_NOG9N/out/bam/NOG9N_markdup.bam; Line number 88
        at net.sf.samtools.SAMTextHeaderCodec.reportErrorParsingLine(SAMTextHeaderCodec.java:234)
        at net.sf.samtools.SAMTextHeaderCodec.parseRGLine(SAMTextHeaderCodec.java:176)
        at net.sf.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:97)
        at net.sf.samtools.BAMFileReader.readHeader(BAMFileReader.java:428)
        at net.sf.samtools.BAMFileReader.<init>(BAMFileReader.java:158)
        at net.sf.samtools.BAMFileReader.<init>(BAMFileReader.java:117)
        at net.sf.samtools.SAMFileReader.init(SAMFileReader.java:545)
        at net.sf.samtools.SAMFileReader.<init>(SAMFileReader.java:170)
        at net.sf.samtools.SAMFileReader.<init>(SAMFileReader.java:125)
        at net.sf.samtools.BamNameIndex.run(BamNameIndex.java:195)
        at net.sf.samtools.BamNameIndex.main(BamNameIndex.java:115)
        ... 5 more
Caused by: java.lang.NumberFormatException: For input string: "Unknown"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at net.sf.samtools.SAMTextHeaderCodec.parseRGLine(SAMTextHeaderCodec.java:173)
        ... 14 more

**Comment by eigoshimizu** [comment]
現在の仕様としては、

1) Job yaml ファイルに自分で指定する場合は、自己責任という感じになります。
2) Job yaml ファイルに指定しない場合は、下記を使用します。
 '@RG\\tID:Unknown\\tSM:Unknown\\tLB:Unknown\\tPL:Unknown\\tPU:Unknown\\tCN:unknown'

ということですが、
ユーザーが PI: に、数字以外を指定する場合があると思いますので、job yaml ファイルチェッカーを genomon.py に組み込んで、bam_read_groupに問題がある場合は、警告を表示して、実行しないようにします。

ご協力ありがとうございます。

**Comment by eigoshimizu** [comment]
実装しました。
PI:　に数字以外のものを指定すると、メッセージを出力して、エラーとなります。
